{
    "openapi": "3.0.0",
    "info": {
        "title": "LaraPoints",
        "description": "LaraPoints REST API skeleton documentation",
        "contact": {
            "email": "ihamzehald@gmail.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://larapoints.loc/api/v1",
            "description": "LaraPoints host"
        }
    ],
    "paths": {
        "/auth/jwt/Register": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "JWT Register",
                "description": "Register a new user",
                "operationId": "jwtRegister",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "description": "User email",
                                        "type": "string",
                                        "example": "ihamzehald@gmail.com"
                                    },
                                    "name": {
                                        "description": "User name",
                                        "type": "string",
                                        "example": "Hamza al darawsheh"
                                    },
                                    "password": {
                                        "description": "User password",
                                        "type": "string",
                                        "example": "larapoints123"
                                    },
                                    "password_confirmation": {
                                        "description": "User password confirmation",
                                        "type": "string",
                                        "example": "larapoints123"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "ok",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Response message",
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "Response data",
                                            "properties": {
                                                "id": {
                                                    "description": "User id",
                                                    "type": "integer"
                                                },
                                                "access_token": {
                                                    "description": "JWT access token",
                                                    "type": "string"
                                                },
                                                "token_type": {
                                                    "description": "Token type",
                                                    "type": "string"
                                                },
                                                "expires_in": {
                                                    "description": "Token expiration in miliseconds",
                                                    "type": "integer"
                                                },
                                                "name": {
                                                    "description": "User name",
                                                    "type": "string"
                                                },
                                                "email": {
                                                    "description": "User email",
                                                    "type": "string"
                                                },
                                                "updated_at": {
                                                    "description": "User updated at",
                                                    "type": "string"
                                                },
                                                "created_at": {
                                                    "description": "User created at",
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        },
                                        "errors": {
                                            "description": "response errors",
                                            "type": "null"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "message": "User logged in successfully",
                                        "data": {
                                            "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sYXJhcG9pbnRzLmxvY1wvYXBpXC92MlwvYXV0aFwvand0XC9yZWdpc3RlciIsImlhdCI6MTU5OTUwNDc0NCwiZXhwIjoxNTk5NTA4MzQ0LCJuYmYiOjE1OTk1MDQ3NDQsImp0aSI6Ik4zTW9Mek9xMHFlS2xmdnIiLCJzdWIiOjE3LCJwcnYiOiI4N2UwYWYxZWY5ZmQxNTgxMmZkZWM5NzE1M2ExNGUwYjA0NzU0NmFhIn0.7oAcjHhMK8kUyQpyXIfpmMC4vk12wJa7PR9KwRYLFMo",
                                            "token_type": "bearer",
                                            "expires_in": 3600,
                                            "name": "Hamzeh test",
                                            "email": "ihamzehald15@gmail.com",
                                            "updated_at": "2020-09-07T18:52:24.000000Z",
                                            "created_at": "2020-09-07T18:52:24.000000Z",
                                            "id": 17
                                        },
                                        "errors": null
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerJWTAuth": []
                    }
                ]
            }
        },
        "/auth/jwt/login": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "JWT login",
                "description": "Login a user and generate JWT token",
                "operationId": "jwtLogin",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "description": "User email",
                                        "type": "string",
                                        "example": "ihamzehald@gmail.com"
                                    },
                                    "password": {
                                        "description": "User password",
                                        "type": "string",
                                        "example": "larapoints123"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "ok",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Response message",
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "Response data",
                                            "properties": {
                                                "access_token": {
                                                    "description": "JWT access token",
                                                    "type": "string"
                                                },
                                                "token_type": {
                                                    "description": "Token type",
                                                    "type": "string"
                                                },
                                                "expires_in": {
                                                    "description": "Token expiration in miliseconds",
                                                    "type": "integer"
                                                }
                                            },
                                            "type": "object"
                                        },
                                        "errors": {
                                            "description": "response errors",
                                            "type": "null"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "message": "User logged in successfully",
                                        "data": {
                                            "access_token": "eyJ0eXAiOiJKV1QiLCJhbGc...",
                                            "token_type": "bearer",
                                            "expires_in": 3600
                                        },
                                        "errors": null
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Response message",
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "Response data",
                                            "type": "null"
                                        },
                                        "errors": {
                                            "description": "response errors",
                                            "properties": {
                                                "wrong_credentials": {
                                                    "description": "Wrong credentials error message",
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "message": "Wrong credentials",
                                        "data": null,
                                        "errors": {
                                            "wrong_credentials": "The provided credentials don't match our records"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerJWTAuth": []
                    }
                ]
            }
        },
        "/auth/jwt/logout": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Log the user out",
                "description": "Log the user out (Invalidate the token)",
                "operationId": "jwtLogout",
                "responses": {
                    "200": {
                        "description": "ok",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Response message",
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "Response data",
                                            "type": "null"
                                        },
                                        "errors": {
                                            "description": "response errors",
                                            "type": "null"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "message": "User logged out successfully",
                                        "data": null,
                                        "errors": null
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Response message",
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "Response data",
                                            "type": "null"
                                        },
                                        "errors": {
                                            "description": "response errors",
                                            "properties": {
                                                "unauthorized": {
                                                    "description": "Unauthorized error message",
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "message": "Unauthorized",
                                        "data": null,
                                        "errors": {
                                            "unauthorized": "Unauthorized request"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerJWTAuth": []
                    }
                ]
            }
        },
        "/auth/jwt/refresh": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh a JWT token",
                "description": "Referesh a JWT token based on the passed JWT token in the header",
                "operationId": "jwtRefresh",
                "responses": {
                    "200": {
                        "description": "ok",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Response message",
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "Response data",
                                            "properties": {
                                                "access_token": {
                                                    "description": "JWT access token",
                                                    "type": "string"
                                                },
                                                "token_type": {
                                                    "description": "Token type",
                                                    "type": "string"
                                                },
                                                "expires_in": {
                                                    "description": "Token expiration in miliseconds",
                                                    "type": "integer"
                                                }
                                            },
                                            "type": "object"
                                        },
                                        "errors": {
                                            "description": "response errors",
                                            "type": "null"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "message": "JWT token refresh successfully",
                                        "data": {
                                            "access_token": "eyJ0eXAiOiJKV1QiLCJhbGc...",
                                            "token_type": "bearer",
                                            "expires_in": 3600
                                        },
                                        "errors": null
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Response message",
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "Response data",
                                            "type": "null"
                                        },
                                        "errors": {
                                            "description": "response errors",
                                            "properties": {
                                                "unauthorized": {
                                                    "description": "Unauthorized error message",
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "message": "Unauthorized",
                                        "data": null,
                                        "errors": {
                                            "unauthorized": "Unauthorized request"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerJWTAuth": []
                    }
                ]
            }
        },
        "/auth/jwt/password/request/reset": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Request reset password",
                "description": "Send OTP code to user email",
                "operationId": "jwtPasswordRequestReset",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "description": "User email",
                                        "type": "string",
                                        "example": "ihamzehald@gmail.com"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "ok",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Response message",
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "Response data",
                                            "type": "null"
                                        },
                                        "errors": {
                                            "description": "response errors",
                                            "type": "null"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "message": "OTP email sent successfully",
                                        "data": null,
                                        "errors": null
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Response message",
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "Response data",
                                            "type": "null"
                                        },
                                        "errors": {
                                            "description": "response errors",
                                            "properties": {
                                                "unauthorized": {
                                                    "description": "Unauthorized error message",
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "message": "Unauthorized",
                                        "data": null,
                                        "errors": {
                                            "unauthorized": "Unauthorized request"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerJWTAuth": []
                    }
                ]
            }
        },
        "/auth/jwt/password/otp/verify": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Verify OTP code",
                "description": "Verify OTP code and return temporary verification code",
                "operationId": "jwtVerifyOTP",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "otp": {
                                        "description": "User OTP",
                                        "type": "string",
                                        "example": "wyHyJ9"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "ok",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Response message",
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "response data",
                                            "properties": {
                                                "verification_token": {
                                                    "description": "Reset password verification token",
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        },
                                        "errors": {
                                            "description": "response errors",
                                            "type": "null"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "message": "OTP verified successfully",
                                        "data": {
                                            "verification_token": "WuKr7Rmrka5jNYu9y6..."
                                        },
                                        "errors": null
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Response message",
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "Response data",
                                            "type": "null"
                                        },
                                        "errors": {
                                            "description": "response errors",
                                            "properties": {
                                                "unauthorized": {
                                                    "description": "Unauthorized error message",
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "message": "Unauthorized",
                                        "data": null,
                                        "errors": {
                                            "unauthorized": "Unauthorized request"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerJWTAuth": []
                    }
                ]
            }
        },
        "/auth/jwt/password/reset": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Reset user password",
                "description": "Reset user password",
                "operationId": "jwtPasswordReset",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "verification_token": {
                                        "description": "verification token from (/auth/jwt/password/otp/verify) end point",
                                        "type": "string",
                                        "example": "SEJJJvD8YbpfXDljgMI3RAXySokNXIRmPT7yB7H2NZcnNSHTJgWUVJyAaExGvDPo"
                                    },
                                    "password": {
                                        "description": "New password",
                                        "type": "string",
                                        "example": "larapoints123"
                                    },
                                    "password_confirmation": {
                                        "description": "New password confirmation",
                                        "type": "string",
                                        "example": "larapoints123"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "ok",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Response message",
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "Response data",
                                            "type": "null"
                                        },
                                        "errors": {
                                            "description": "response errors",
                                            "type": "null"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "message": "Password reset successfully",
                                        "data": null,
                                        "errors": null
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Response message",
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "Response data",
                                            "type": "null"
                                        },
                                        "errors": {
                                            "description": "response errors",
                                            "properties": {
                                                "unauthorized": {
                                                    "description": "Unauthorized error message",
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "message": "Unauthorized",
                                        "data": null,
                                        "errors": {
                                            "unauthorized": "Unauthorized request"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerJWTAuth": []
                    }
                ]
            }
        },
        "/user/me": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Get the authenticated User",
                "description": "Get the authenticated User",
                "operationId": "UserMe",
                "responses": {
                    "200": {
                        "description": "ok",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Response message",
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "Response data",
                                            "type": "object",
                                            "$ref": "#/components/schemas/User"
                                        },
                                        "errors": {
                                            "description": "response errors",
                                            "type": "null"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "message": "JWT token refresh successfully",
                                        "data": {
                                            "id": 1,
                                            "name": "Hamza al darawsheh",
                                            "email": "ihamzehald@gmail.com",
                                            "email_verified_at": null,
                                            "created_at": "2020-03-20T09:10:32.000000Z",
                                            "updated_at": "2020-05-08T20:39:06.000000Z"
                                        },
                                        "errors": null
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "description": "Response message",
                                            "type": "string"
                                        },
                                        "data": {
                                            "description": "Response data",
                                            "type": "null"
                                        },
                                        "errors": {
                                            "description": "response errors",
                                            "properties": {
                                                "unauthorized": {
                                                    "description": "Unauthorized error message",
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "message": "Unauthorized",
                                        "data": null,
                                        "errors": {
                                            "unauthorized": "Unauthorized request"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerJWTAuth": []
                    }
                ]
            }
        }
    },
    "components": {
        "schemas": {
            "User": {
                "properties": {
                    "id": {
                        "schema": "User",
                        "description": "User ID",
                        "type": "string"
                    },
                    "name": {
                        "schema": "User",
                        "description": "User name",
                        "type": "string"
                    },
                    "email": {
                        "schema": "User",
                        "description": "User email",
                        "type": "string"
                    },
                    "email_verified_at": {
                        "schema": "User",
                        "description": "Email verified at",
                        "type": "string"
                    },
                    "created_at": {
                        "schema": "User",
                        "description": "Created at",
                        "type": "string"
                    },
                    "updated_at": {
                        "schema": "User",
                        "description": "Updated at",
                        "type": "string"
                    }
                },
                "type": "object",
                "xml": {
                    "name": "User"
                }
            }
        },
        "securitySchemes": {
            "bearerJWTAuth": {
                "type": "http",
                "description": "Oauth2 security",
                "name": "oauth2",
                "in": "header",
                "flows": {
                    "clientCredentials": {
                        "tokenUrl": "oauth/token",
                        "scopes": {}
                    }
                },
                "bearerFormat": "JWT",
                "scheme": "bearer"
            }
        }
    }
}